# Generated by Django 2.2.9 on 2021-08-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='things',
            name='used',
            field=models.BooleanField(default=None),
        ),
    ]
