# Generated by Django 2.2.9 on 2021-08-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20210831_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroes',
            name='alive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='things',
            name='used',
            field=models.BooleanField(default=0),
        ),
    ]
