# Generated by Django 2.2.9 on 2021-08-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20210831_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroes',
            name='count_death',
            field=models.IntegerField(default=0),
        ),
    ]
