# Generated by Django 2.2.9 on 2021-08-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_heroes_count_death'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroes',
            name='count_wins',
            field=models.IntegerField(default=0),
        ),
    ]
